# The file to run cicd pipeline

name: Run Tests

on:
    push:
      branches:
        - main
        - test
        - "feature/**"
    pull_request:
      branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  #can be changed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies

      - name: Run pytest
        run: |
          pytest --maxfail=3 --disable-warnings -v
      
      - name : Passes test
        if: failure()
        run: echo "Tests or code quality checks failed!"
